//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Good : INotifyPropertyChanged
    {
        private string _productName;
        private decimal? _price;

        public int ID { get; set; }
        public string ProductName { get => _productName; set { _productName = value; Notify(); } }
        public Nullable<decimal> Price { get => _price; set { _price = value; Notify(); } }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ManufactureId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        #region Notify
        void Notify([CallerMemberName] string propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        public event PropertyChangedEventHandler PropertyChanged;
        #endregion
    }
}
